version: '3.8'

services:
  cassandra:
    image: 'cassandra:3.11'
    container_name: cassandra
    hostname: cassandra
    environment:
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=1G
      - CASSANDRA_CLUSTER_NAME=thp
    ports:
      - '7000:7000'
    volumes:
      - './vol/cassandra/data:/var/lib/cassandra/data'
    networks:
      - hiveNet

  thehive:
    image: 'thehiveproject/thehive4:latest'
    container_name: thehive4
    restart: unless-stopped
    depends_on:
      - cassandra
    ports:
      - '9000:9000'
    volumes:
      - ./vol/thehive/application.conf:/etc/thehive/application.conf
      - ./vol/thehive/data:/opt/thp/thehive/data
      - ./vol/thehive/index:/opt/thp/thehive/index
    command: '--no-config --no-config-secret'
    networks:
      - hiveNet

  elasticsearch:
    image: 'elasticsearch:7.8.1'
    container_name: elasticsearch
    hostname: elasticsearch
    restart: unless-stopped
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - script.allowed_types=inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
    ports:
      - '9200:9200'
    networks:
      - hiveNet

  cortex:
    image: 'thehiveproject/cortex:latest'
    container_name: cortex
    hostname: cortex
    restart: unless-stopped
    environment:
      - job_directory=${job_directory}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./vol/cortex/application.conf:/etc/cortex/application.conf
      - ${job_directory}:${job_directory}
    depends_on:
      - elasticsearch
    ports:
      - '9001:9001'
    networks:
      - hiveNet

networks:
  hiveNet: 
    driver: bridge